- hosts: vagrant
  become: yes
  become_user: root
  tasks:
    - name: Install nginx
      yum: name=nginx state=latest
      tags:
        - install

    - name: Upload file that doc.html to server
      copy: src=doc.html dest=/usr/share/nginx/html/
      tags:
        - upload_file

    - name: Upload file that nginx.conf to server
      copy: src=nginx.conf dest=/etc/nginx/
      tags:
        - upload_file

    - name: Startup Nginx
      service: name=nginx state=started enabled=yes
      tags:
        - startup
